version: "3.8"

services:
  admin-backend:
    image: idkwhatnametoput/gaming-cafe-admin-backend:latest
    restart: always
    container_name: gaming-cafe-admin-backend-container
    environment:
      PORT: 5001
      ADMIN_PORT: 5001
      NODE_ENV: development
      MONGODB_URI: mongodb://e2425-wads-l4bcg4:ciwrot6o@10.25.143.17:27017/e2425-wads-l4bcg4?authSource=e2425-wads-l4bcg4
      JWT_SECRET: idkwhattoputheresoiwillusethis
      ADMIN_JWT_SECRET: admin-secret-key-for-ichi-gaming-cafe-2025
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_EMAIL: admin@ichi.com
      DEFAULT_ADMIN_PASSWORD: admin123
      DEFAULT_ADMIN_FULLNAME: System Administrator
      GAMING_HOURLY_RATE: 20000
      PREMIUM_HOURLY_RATE: 25000
      LOW_STOCK_THRESHOLD: 5
    ports:
      # CONSISTENT MAPPING: external:internal
      - "3109:5001"
    networks:
      - gaming-cafe-admin-network

  admin-frontend:
    image: idkwhatnametoput/gaming-cafe-admin-frontend:latest
    restart: always
    container_name: gaming-cafe-admin-frontend-container
    depends_on:
      - admin-backend
    ports:
      # CONSISTENT MAPPING: both external and internal use same port
      - "3107:3107"  # This way nginx config matches
    networks:
      - gaming-cafe-admin-network

networks:
  gaming-cafe-admin-network:
    driver: bridge
    name: gaming-cafe-admin-net